feat: add index classes
googleapis/langchain-google-cloud-sql-pg-python pull request #12
Opened 2024-02-09 18:56 UTC by averikitsch

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/langchain-google-cloud-sql-pg-python/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2024-02-09 20:06 UTC, kurtisvg requested changes

2024-02-09 20:06 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/indexes.py
> +    COSINE = "cosine"
```suggestion
    COSINE_DISTANCE = "cosine"
```

2024-02-09 20:06 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/indexes.py
> +class DistanceStrategy(str, enum.Enum):
```suggestion
class DistanceStrategy(enum.Enum):
```

2024-02-09 20:06 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/indexes.py
> +class BruteForce:
Can we have an abstract base class between all of these?

2024-02-09 20:06 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/indexes.py
> +        name: str = "langchainhnsw",
I think we decided we should have a common default name here

2024-02-09 20:06 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/indexes.py
> +DEFAULT_DISTANCE_STRATEGY = DistanceStrategy.COSINE
Why cosign?

2024-02-09 20:06 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/indexes.py
> +class HNSWIndex:
Any reason not to use `@dataclass`?

2024-02-09 20:06 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/indexes.py
> +    class QueryOptions:
How do we plan on using this?

2024-02-12 17:55 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/indexes.py
> +DEFAULT_DISTANCE_STRATEGY = DistanceStrategy.COSINE
https://platform.openai.com/docs/guides/embeddings/which-distance-function-should-i-use

2024-02-13 17:59 UTC, closed without merging