fix: update from_engine
googleapis/langchain-google-cloud-sql-pg-python pull request #120
Opened 2024-04-22 19:44 UTC by averikitsch

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/langchain-google-cloud-sql-pg-python/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2024-04-24 16:37 UTC, kurtisvg approved these changes

2024-04-24 16:37 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/engine.py
> +    async def afrom_engine(cls, engine: AsyncEngine) -> PostgresEngine:
This is a breaking change -- we need to make sure to update the commit message to something like: "fix!: rename from_engine to afrom_engine"

2024-04-24 16:48 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_pg/engine.py
> +    async def afrom_engine(cls, engine: AsyncEngine) -> PostgresEngine:
Why do we need an `afrom_engine`, the initialization of a SQLAlchemy async engine is synchronous. Thus wouldn't we want to support `from_engine`?

2024-04-30 00:04 UTC, jackwotherspoon requested changes
I still do not understand why we need two `from_engine` methods? There should be no need for an async `from_engine` since the init of an async engine is sync code...

2024-04-30 00:04 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_pg/engine.py
> +    def from_engine(cls, engine: AsyncEngine) -> PostgresEngine:
is this supposed to be async?

2024-04-30 17:42 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/engine.py
> +    def from_engine(cls, engine: AsyncEngine) -> PostgresEngine:
You are right, the one method can support both the sync and async environments. We need to save the loop in order for the engine to be able to use sync methods.

2024-04-30 20:49 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_pg/engine.py
> +        loop: Optional[asyncio.AbstractEventLoop] = None,
I need to take a deep look at this and think it through fully. Nowadays in Python we are really trying to now have any users deal with `loop` params. It leads to all sorts of issues if the user has the ability to configure the event loop.

I wonder if we can maybe lazy init somehow. Like try `asyncio.get_running_loop()` and if it errors set `loop=None` and then later on when we can guarantee we are in async land we set loop.

I have to think about this design as its tricky.

2024-08-02 22:16 UTC, closed without merging