feat: add Vector Store
googleapis/langchain-google-cloud-sql-pg-python pull request #14
Opened 2024-02-09 23:46 UTC by averikitsch

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/langchain-google-cloud-sql-pg-python/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2024-02-10 02:41 UTC, kurtisvg requested changes

2024-02-10 02:41 UTC, kurtisvg commented on pyproject.toml
> +    "langchain==0.1.1",
Should this be 'langchain" or "langchain-core"?

2024-02-10 02:41 UTC, kurtisvg commented on pyproject.toml
> +    "nest_asyncio>=1.6.0",
Can we removee this?

2024-02-10 02:41 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/cloudsql_vectorstore.py
> +            await self.engine._aexecute(f"TRUNCATE TABLE {self.table_name}")
nit: I'm not sure I like this here...

2024-02-10 02:41 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/cloudsql_vectorstore.py
> +                del all_columns[column]
This doesn't seem quite right -- shouldn't we figure out what  metadata_columns is before we check contents?

2024-02-10 02:41 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/cloudsql_vectorstore.py
> +            ids = ["NULL" for _ in texts]
Can we not just us None here?

2024-02-10 02:41 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/cloudsql_vectorstore.py
> +            return self.engine.run_as_sync(self.aadd_texts(texts, metadatas, ids))
Are we doing this pattern enough we should just shove it into run_as_sync?

2024-02-10 02:41 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/cloudsql_vectorstore.py
> +            return False
nit: happy path is default path
```suggestion
        if not ids:
            return False
            
        id_list = ", ".join([f"'{id}'" for id in ids])
        query = (
            f"DELETE FROM {self.table_name} WHERE {self.id_column} in ({id_list})"
        )
        await self.engine._aexecute(query)
        return True
```

2024-02-10 02:41 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/cloudsql_vectorstore.py
> +        return []
assume this is TODO?

2024-02-10 02:41 UTC, kurtisvg commented on tests/test_cloudsql_vectorstore.py
> +class FakeEmbeddingsWithDimension(FakeEmbeddings):
nit: should we use DeterministicFakeEmbeddings? https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/embeddings/fake.py#L25

2024-02-12 00:21 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/cloudsql_vectorstore.py
> +                del all_columns[column]
Added comments. We are using either metadata columns or ignore metadata columns. If the first, check to make sure all columns exists. If using ignore I am filtering out known columns to find the list of columns to use.

2024-02-12 00:21 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/cloudsql_vectorstore.py
> +            ids = ["NULL" for _ in texts]
No the sql statement errors

2024-02-12 00:23 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/cloudsql_vectorstore.py
> +        return []
Yes, will be in another PR

2024-02-12 02:07 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/cloudsql_vectorstore.py
> +            await self.engine._aexecute(f"TRUNCATE TABLE {self.table_name}")
Should we remove this feature altogether?

2024-02-12 15:54 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/cloudsql_vectorstore.py
> +            await self.engine._aexecute(f"TRUNCATE TABLE {self.table_name}")
Probably? I'm squeamish of the idea that TRUNCATE will destroy the data before the verification checks are done. But maybe it's best to just leave it out to prevent a footgun?

2024-02-12 16:57 UTC, kurtisvg approved these changes

2024-02-12 16:57 UTC, kurtisvg commented on pyproject.toml
> +    "nest_asyncio>=1.6.0",
I think we should try to remove this

2024-02-12 17:01 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/cloudsql_vectorstore.py
> +                del all_columns[column]
Ah makes sense, thanks for clarifying.

2024-02-12 21:59 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/cloudsql_vectorstore.py
> +            await self.engine._aexecute(f"TRUNCATE TABLE {self.table_name}")
Removed

2024-02-13 02:28 UTC, merged