chore(samples): add Reasoning Engine Samples
googleapis/langchain-google-cloud-sql-pg-python pull request #150
Opened 2024-06-28 23:06 UTC by averikitsch

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/langchain-google-cloud-sql-pg-python/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2024-07-02 18:21 UTC, kurtisvg requested changes

2024-07-02 18:21 UTC, kurtisvg commented on samples/reasoning_engine/README.md
> +[Reasoning Engine](https://cloud.google.com/vertex-ai/generative-ai/docs/reasoning-engine/overview)
Do we have explicit guidance on how to message w.r.t. Reasoning Engine vs LangChain on Vertex AI?

2024-07-02 18:21 UTC, kurtisvg commented on samples/reasoning_engine/README.md
> +## Before you begin
nit: should this section precede templates?

2024-07-02 18:21 UTC, kurtisvg commented on samples/reasoning_engine/clean_up.py
> +TEST_NAME = os.getenv("DISPLAY_NAME")
Can we put this in a single file and import it from the others?

2024-07-02 18:21 UTC, kurtisvg commented on samples/reasoning_engine/clean_up.py
> +        user="postgres",
is postgres the right user?

2024-07-02 18:21 UTC, kurtisvg commented on samples/reasoning_engine/create_embeddings.py
> +        print(e)
Not sure we should catch this exception ?

2024-07-02 18:21 UTC, kurtisvg commented on samples/reasoning_engine/create_embeddings.py
> +        ),
nit: 
```suggestion
            model_name="textembedding-gecko@latest", 
            project=PROJECT_ID,
        ),
```

2024-07-02 18:21 UTC, kurtisvg commented on samples/reasoning_engine/prebuilt_langchain_agent_template.py
> +# Create this table using `PostgresEngine` method: init_vectorstore_table()
Should they run the create_embeddings file?

2024-07-02 18:21 UTC, kurtisvg commented on samples/reasoning_engine/prebuilt_langchain_agent_template.py
> +    engine = PostgresEngine.from_instance(
Should this engine be a global variable? Or at least globally memoized?

2024-07-02 18:21 UTC, kurtisvg commented on samples/reasoning_engine/prebuilt_langchain_agent_template.py
> +    vector_store = PostgresVectorStore.create_sync(
same here w.r.t. reusing object

2024-07-02 18:21 UTC, kurtisvg commented on samples/reasoning_engine/retriever_chain_template.py
> +print(remote_app.query(input="movies about engineers"))
Any reason not to wrap this in a 'main'? Maybe use argparse to add a --local flag for the local bits instead of uncommenting?

2024-07-02 21:59 UTC, averikitsch commented on samples/reasoning_engine/README.md
> +## Before you begin
I want to highlight the templates over the getting started instructions

2024-07-02 22:02 UTC, averikitsch commented on samples/reasoning_engine/create_embeddings.py
> +        print(e)
I was going to create and delete the database each time but it's easier to delete tables from the database; therefore I don't really care about this error. The duplicate database error is hard to catch because the sqlalchemy changes it to just an OperationalError.

2024-07-02 22:04 UTC, averikitsch commented on samples/reasoning_engine/create_embeddings.py
> +        ),
This breaks the linter

2024-07-02 22:19 UTC, averikitsch commented on samples/reasoning_engine/retriever_chain_template.py
> +print(remote_app.query(input="movies about engineers"))
I wanted to focus on the deployment story rather than the local experience as well as not wanting to add extra complexity with the CLI. Samples CLIs are not recommended.

2024-07-02 22:22 UTC, averikitsch commented on samples/reasoning_engine/prebuilt_langchain_agent_template.py
> +    engine = PostgresEngine.from_instance(
That would be a better story for multiple tools using the same engine/vector store. Do you think that complicates the conciseness of this sample?

2024-07-02 22:24 UTC, averikitsch commented on samples/reasoning_engine/clean_up.py
> +TEST_NAME = os.getenv("DISPLAY_NAME")
Yes, but for the template files we would have to add a field to the create reasoning engine method like  `extra_packages: ["config.py"],`. Do you think that complicates the simplicity of this sample?

2024-07-03 22:11 UTC, kurtisvg requested changes

2024-07-03 22:11 UTC, kurtisvg commented on samples/reasoning_engine/clean_up.py
> +TEST_NAME = os.getenv("DISPLAY_NAME")
I think we should pick one between:
1. Asking them to edit the file and using a single file
2. Asking them to use env vars 

If the change is just one line it seems pretty reasonable for the benefit of not needing to update it 5 different times.

2024-07-03 22:11 UTC, kurtisvg commented on samples/reasoning_engine/create_embeddings.py
> +        print(e)
Ok -- slightly concerned that it'll mask other things like connectivity errors. I think at a minimum we should leave a comment why it's okay to hide this error.

This is how we handled in in the DB retrieval app fwiw: https://github.com/GoogleCloudPlatform/genai-databases-retrieval-app/blob/00d8ddd5d0c3df45c206ed89af4fb6a69bb7c19c/retrieval_service/datastore/providers/cloudsql_postgres_test.py#L81

We probably need to dispose the engine regardless?

2024-07-03 22:11 UTC, kurtisvg commented on samples/reasoning_engine/retriever_chain_template.py
> +print(remote_app.query(input="movies about engineers"))
OK -- will downgrade to a nit, but my 2c is I like to be able to run the file without git yelling at me :)

2024-07-03 22:11 UTC, kurtisvg commented on samples/reasoning_engine/prebuilt_langchain_agent_template.py
> +    engine = PostgresEngine.from_instance(
So I'd rather show folks the right way to do this and be slightly more complicated than the wrong way and they are left in the dark in how it should actually work. 

Connection pooling correctly is a thing folks struggle with, so I'd rather do the extra work to show them how to do it correctly from the start.

2024-07-08 21:02 UTC, averikitsch commented on samples/reasoning_engine/prebuilt_langchain_agent_template.py
> +    engine = PostgresEngine.from_instance(
This unfortunately is not feasible since Reasoning Engine pickles the code. We may need to add support in the future similar to https://github.com/googleapis/python-aiplatform/issues/3710

2024-07-09 15:37 UTC, kurtisvg commented on samples/reasoning_engine/prebuilt_langchain_agent_template.py
> +    engine = PostgresEngine.from_instance(
We can't even use the "set_up" function to set these up? https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/reasoning-engine#deploy_an_advanced_app_configuration

2024-07-09 16:26 UTC, averikitsch commented on samples/reasoning_engine/prebuilt_langchain_agent_template.py
> +    engine = PostgresEngine.from_instance(
We can, but that defeats the point of this example. The other examples show how to use set_up()

2024-07-10 16:43 UTC, averikitsch commented on samples/reasoning_engine/prebuilt_langchain_agent_template.py
> +    engine = PostgresEngine.from_instance(
Updating from offline - we can use a lazy initialization to share connection pooling.

2024-07-10 16:58 UTC, kurtisvg approved these changes

2024-07-10 17:07 UTC, merged