feat: Support IAM account override
googleapis/langchain-google-cloud-sql-pg-python pull request #160
Opened 2024-07-17 14:23 UTC by duwenxin99

Allow user to override default IAM credentials

2024-07-18 13:22 UTC, jackwotherspoon requested changes

2024-07-18 13:22 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_pg/engine.py
> +        service_account_email: Optional[str] = None,
I wonder if `iam_account_email` is a better argument name than `service_account_email`?

I could run `gcloud auth application-default login` to set my IAM USER account as the ADC and not a service account. Thus the email I would pass in here would be an IAM user email not an IAM service account email.

`iam_account_email` is inclusive of IAM user emails and IAM service account emails.

2024-07-18 18:48 UTC, jackwotherspoon commented
@duwenxin99 should we add an integration test for this?

2024-07-19 21:12 UTC, averikitsch commented on tests/test_postgresql_engine.py
> +        iam_account,
missing @pytest.fixture for iam_account in this Sync class

2024-07-21 19:37 UTC, duwenxin99 commented on tests/test_postgresql_engine.py
> +        db_project,
updated

2024-07-21 19:37 UTC, duwenxin99 commented on tests/test_postgresql_engine.py
> +        iam_account,
updated

2024-07-22 12:16 UTC, jackwotherspoon approved these changes
LGTM ✅

2024-07-22 22:19 UTC, averikitsch approved these changes

2024-07-23 04:41 UTC, merged