feat: added vector store initialization from documents
googleapis/langchain-google-cloud-sql-pg-python pull request #174
Opened 2024-07-29 06:54 UTC by vishwarajanand

Fixes [b/343215179](http://b/343215179) 🦕

2024-07-29 12:46 UTC, jackwotherspoon reviewed
This PR should use the `docs:` conventional commit prefix, as this is not a feature in the library itself and is purely a documentation change.

See [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) for more details.

2024-07-29 12:46 UTC, jackwotherspoon commented on docs/vector_store.ipynb
> +        "### Initialize Vector Store with Documents from Any Source\n"
nit: match style of previous headings
```suggestion
        "### Initialize Vector Store with documents from any source\n"
```

2024-07-29 20:39 UTC, averikitsch requested changes
Please see comment on AlloyDB PR. Let's discuss a better placement of this info

2024-08-02 22:08 UTC, averikitsch approved these changes

2024-08-02 22:14 UTC, merged