fix: add support for cross environment usage
googleapis/langchain-google-cloud-sql-pg-python pull request #176
Opened 2024-07-31 23:48 UTC by averikitsch

Due to the use of an async driver, sync and async interfaces can not be mixed with the opposite environment.
If the Engine was initialized asynchronously, no self-managed loop is created therefore coroutines can not be scheduled to run synchronously. 
* If we try to run on the same loop, the task blocks the thread with the current loop and never completes.
* If the Engine was initialized synchronously, coroutines error since it is not attached to the native loop. 
LangChain interfaces support both async and sync calls for all methods. 

https://docs.google.com/document/d/1Cf73cs5hTV0rCakK7rjZAPLk9RIsw1AS7o7GcDoTQg0

2024-08-02 16:00 UTC, jackwotherspoon commented
@averikitsch do you mind adding a brief PR description going over what this `fix:` is fixing? :smile:

2024-08-02 16:16 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_pg/engine.py
> +        thread.start()
what is the need to schedule async functions in a background thread? This will result in "running on different loop" errors I believe...

2024-08-02 18:41 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/engine.py
> +        thread.start()
We need to be able to support both Async and Sync methods on the vectorstore. Currently, the vector store only supports Async when initialized Async and only support Sync when initialized Sync. Therefore we need to run everything on a background loop to achieve the cross env support. Full notes are now linked in the description.

2024-08-19 14:50 UTC, kurtisvg requested changes

2024-08-19 14:50 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/engine.py
> +        return cls(cls.__create_key, engine, loop, thread)
I have concerns about this bit -- if we are using a different loop than the engine was initialized with, shouldn't we be getting running on different loop errors here? 

My concern is we either:
1. aren't testing enough to capture these errors
2. are mixing up loops somehow and not actually running the engine in the background

2024-08-19 14:50 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/engine.py
> +        thread = Thread(target=loop.run_forever, daemon=True)
There is at least one issue I noticed where we are caching the Cloud SQL Connector but not the loop. I think we need to cache these together? So maybe we have one default "loop"/thread at the class level?

2024-08-21 18:05 UTC, closed without merging