feat: refactor vector store to wrap async class
googleapis/langchain-google-cloud-sql-pg-python pull request #187
Opened 2024-08-22 16:25 UTC by averikitsch

Current diff is against async-only branch

2024-08-27 21:27 UTC, kurtisvg requested changes

2024-08-27 21:27 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/vectorstore.py
> +        embedding_service: Embeddings,
breaking change?

2024-08-27 21:27 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/vectorstore.py
> +        vs = cls(cls.__create_key, engine, async_vs)
nit: should use create method

2024-08-27 21:27 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/vectorstore.py
> +        index_query_options: Optional[QueryOptions] = None,
Need to update the docstring

2024-08-27 21:27 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/vectorstore.py
>              return self._euclidean_relevance_score_fn
Should this be implemented in the underlying vectorstore?

2024-08-27 21:27 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/vectorstore.py
>              return self._euclidean_relevance_score_fn
follow up: probbaly not, looks like it's relying on inherit values? should confirm

2024-08-27 21:27 UTC, kurtisvg commented on src/langchain_google_cloud_sql_pg/vectorstore.py
> +    async def ais_valid_index(
this is breaking change, make sure we flag in commit message

2024-08-28 00:16 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/vectorstore.py
>              return self._euclidean_relevance_score_fn
I added a comment that this is used for similarity_search_with_relevance_scores() which is predefined by the interface and calls other defined mehtods. The tests are passing.

2024-08-28 15:29 UTC, kurtisvg approved these changes

2024-08-28 17:30 UTC, merged