CloudSQL Postgresql Loader and Saver with Integration Tests
googleapis/langchain-google-cloud-sql-pg-python pull request #19
Opened 2024-02-13 14:59 UTC by ram-searce

Changes Done
  - Added the latest postgresql_engine file
  - Added Loader and Saver class with all methods
  - Postgresql Engine class is used as is
  - Integration Tests added

Changes to be done
  - Code cleanup
  - [P3] Set timeout for query
  - [P2] Convert to VectorStore
  - Code Cleanup
  - Two Integration Tests are failing.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/langchain-google-cloud-sql-pg-python/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2024-02-14 00:50 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/postgresql_engine.py
> +        await self._aexecute(f"DROP TABLE IF EXISTS {table_name}")
Remove Drop table

2024-02-14 00:50 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/postgresql_loader.py
> +        *,
remove

2024-02-14 00:50 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/postgresql_loader.py
> +        query: str = None,
wrap in Optional

2024-02-14 00:50 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/postgresql_loader.py
> +        metadata_json_column: Optional[str] = None,
Can the default be set here rather than below?

2024-02-14 00:50 UTC, averikitsch commented
/gcbrun

2024-02-14 00:51 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/postgresql_loader.py
> +from __future__ import annotations
Add header (https://github.com/googleapis/langchain-google-cloud-sql-pg-python/pull/19/files#diff-e19e0ab3a81357c993d38bcebd746d4a5ed735fd16f6fd24778eca914cc56fceL1-L13)

2024-02-14 00:52 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/postgresql_loader.py
> +from postgresql_engine import PostgreSQLEngine
```suggestion
from .postgresql_engine import PostgreSQLEngine
```

2024-02-14 07:03 UTC, ram-searce commented on src/langchain_google_cloud_sql_pg/postgresql_engine.py
> +        await self._aexecute(f"DROP TABLE IF EXISTS {table_name}")
Updating this in the next commit

2024-02-14 07:03 UTC, ram-searce commented on src/langchain_google_cloud_sql_pg/postgresql_loader.py
> +from __future__ import annotations
Added header in the next commit

2024-02-14 07:23 UTC, ram-searce commented on src/langchain_google_cloud_sql_pg/postgresql_loader.py
> +        *,
Addressed in next commit

2024-02-14 18:17 UTC, averikitsch reviewed
Undo deletion of the gitignore and pyproject.toml

2024-02-14 18:18 UTC, averikitsch commented
/gcbrun

2024-02-14 18:25 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/postgresql_loader.py
> +        table_name: str,
If there is time can we add customization for content_column, metadata_column, and metadata_json_column?

2024-02-14 18:30 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/postgresql_loader.py
> +            values = values if len(values) > 1 else f"('{values[0]}')"  # Unpack single-element tuple
Why is this needed?

2024-02-15 03:18 UTC, ram-searce commented on src/langchain_google_cloud_sql_pg/postgresql_loader.py
> +            values = values if len(values) > 1 else f"('{values[0]}')"  # Unpack single-element tuple
A single element Tuple will still have a comma at the end. eg ("Value1",). Now this will error out in INSERT query. So either we have to treat everything as string and process, or create a tuple and only if len < 1, pick the value and wrap in ()

2024-02-15 03:54 UTC, ram-searce commented
> Undo deletion of the gitignore and pyproject.toml

This is done

2024-02-15 03:55 UTC, ram-searce commented on src/langchain_google_cloud_sql_pg/postgresql_loader.py
> +        table_name: str,
Yes, I am in middle of implementation. As part of this commit itself you would see a partially implemented file and an integration test(which will fail).

2024-02-15 19:23 UTC, averikitsch commented
/gcbrun

2024-02-15 19:26 UTC, averikitsch commented on tests/test_postgresql_loader.py
> +table_name = os.environ["TABLE_NAME"]
Please set this name

2024-02-15 19:26 UTC, averikitsch commented on tests/test_postgresql_loader.py
> +db_name = os.environ["DB_NAME"]
Please generate this name with UUID so tests can run in parallel

2024-02-15 20:51 UTC, averikitsch commented
/gcbrun

2024-02-15 20:57 UTC, averikitsch requested changes

2024-02-15 20:57 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/postgresql_engine.py
> +        metadata = sqlalchemy.MetaData()
Need to import

2024-02-15 20:57 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/postgresql_loader.py
> +        documents = asyncio.run_coroutine_threadsafe(self._collect_async_items(self.alazy_load()), self._loop).result()
Use engine's run_as_sync

2024-02-15 20:57 UTC, averikitsch commented on src/langchain_google_cloud_sql_pg/postgresql_engine.py
> +        query = f"""CREATE TABLE {table_name}(
Wrap table name and column names in quotes

2024-02-16 16:55 UTC, averikitsch commented
/gcbrun

2024-02-16 17:03 UTC, averikitsch commented
/gcbrun

2024-02-20 22:14 UTC, averikitsch commented
Closing in favor of #49

2024-02-20 22:14 UTC, closed without merging