docs: Update sample python notebooks to reflect the support for custo…
googleapis/langchain-google-cloud-sql-pg-python pull request #204
Opened 2024-09-06 11:33 UTC by anubhav756

…me schema.

Specifying custom database schema names is now supported by all library methods. The same is now highlighted in the python notebooks.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/langchain-google-cloud-sql-pg-python/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #175 🦕

2024-09-06 21:34 UTC, averikitsch requested changes

2024-09-06 21:34 UTC, averikitsch commented on samples/langchain_quick_start.ipynb
> +            "cell_type": "markdown",
Can you remove this change? This quickstart is a tutorial rather than how-to documentation

2024-09-06 21:34 UTC, averikitsch commented on docs/chat_message_history.ipynb
> +        ")"
The code blocks are missing the code closing markdown tag "```".

2024-09-06 21:34 UTC, averikitsch commented on docs/chat_message_history.ipynb
> +    },
In each colab, can you also add a note to each of the interfaces? For example for section "Initialize a default PostgresVectorStore" you could add the same note or add it as a commented out field like:
```python
store = await PostgresVectorStore.create( 
    engine=engine,
    table_name=TABLE_NAME,
    # schema_name=SCHEMA_NAME,
    embedding_service=embedding,
)
```

2024-09-12 06:57 UTC, anubhav756 commented on docs/chat_message_history.ipynb
> +    },
Thanks for the suggestion! 🙂

2024-09-12 06:57 UTC, anubhav756 commented on docs/chat_message_history.ipynb
> +        ")"
Thanks for pointing that out!

2024-09-12 19:46 UTC, averikitsch approved these changes

2024-09-13 06:52 UTC, merged