Adding the code lab notebook
googleapis/langchain-google-cloud-sql-pg-python pull request #36
Opened 2024-02-17 00:41 UTC by totoleon

Adding the code lab notebook

2024-02-17 00:43 UTC, loeng2023 commented
https://github.com/googleapis/langchain-google-cloud-sql-pg-python/blob/codelab-demo/samples/langchain_quick_start.ipynb

2024-02-22 22:55 UTC, kurtisvg requested changes

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "In this codelab you will learn how to create an interactive generative AI application with Retrieval Augmented Generation using Cloud SQL Postgres and langchain. We will be creating an applicati
```suggestion
    "In this codelab you will learn how to create an interactive generative AI application with Retrieval Augmented Generation using Cloud SQL Postgres and LangChain. We will be creating an application grounded in a Netflix Movie dataset."
```

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "* How to deploy a Cloud SQL Postgres instance\n",
nit: please fix elsewhere as well
```suggestion
    "* How to deploy a Cloud SQL for PostgreSQL instance\n",
```

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "* How to use Cloud SQL Postgres for chat history storage"
nit: consider linking to LC docs on these interfaces as well 
```suggestion
    "* How to use Cloud SQL Postgres as a VectorStore\n",
    "* How to use Cloud SQL Postgres as a DocumentLoader\n",
    "* How to use Cloud SQL Postgres for ChatHistory storage"
```

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "project_id = \"hailongli-playground2\"  # @param {type:\"string\"}\n",
```suggestion
    "project_id = \"your_project_id\"  # @param {type:\"string\"}\n",
```

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "2. Enable the [Cloud SQL Admin API][admin-api] within your project.\n",
This is enable the Cloud SQL Admin API and the (presumably) Vertex AI API? Can we update this sentence to reflect that as well

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "instance_name = \"codelab-pg-langchain-2\" #@param {type:\"string\"}\n",
nit:
```suggestion
    "instance_name = \"YOUR-INSTANCE-NAME\" #@param {type:\"string\"}\n",
```

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "database_name = \"langchain-test\" #@param {type:\"string\"}\n",
```suggestion
    "database_name = \"YOUR-DB-NAME\" #@param {type:\"string\"}\n",
```

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "  !gcloud sql instances create {instance_name} --database-version=POSTGRES_14 \\\n",
nit: Should we use PG15?

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "> Indented block\n",
is this supposed to be there?

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "Now that you have your database, you will need to import data! We will be using a Netflix Dataset which can be accessed [here](https://www.kaggle.com/datasets/shivamb/netflix-shows). Here are so
```suggestion
    "Now that you have your database, you will need to import data! We will be using a [Netflix Dataset from Kaggle](https://www.kaggle.com/datasets/shivamb/netflix-shows). Here is what the data looks like:"
```

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "!pip install langchain_core"
We already install langchain_core above? Does this still need to be here?

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "    return docs"
I think a more pythonic approach would be:
```python
docs = list(doc async for doc in loader.alazy_load())
for doc in documents[:5]:
    print(doc)
```

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "pg_engine = PostgreSQLEngine.from_instance(\n",
We're using the async methods everywhere else -- should we use `PostgreSQLEngine.afrom_instance`?

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "    overwrite_existing=True,\n",
nit: do we need this?

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "    store_metadata=True,\n",
doesn't this default to true?

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "    model_name=\"textembedding-gecko@latest\", project=project_id\n",
nit: it's a best practice to pin to a specific version. Should we do that here?

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "    password=password,\n",
should these be inputs?

specifically I don't know if we want to recommend to user to use the postgres user

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "vector_store = PostgresVectorStore.create_sync(\n",
any reason not to use async create?

2024-02-22 22:55 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "pg_engine.run_as_sync(pg_engine.init_chat_history_table(table_name=message_table_name))\n",
should use await here instead

2024-02-22 23:56 UTC, tabbyl21 commented on samples/langchain_quick_start.ipynb
> +    "* How to use Cloud SQL Postgres for chat history storage"
@kurtisvg  isn't vector store two words

2024-02-22 23:56 UTC, tabbyl21 commented on samples/langchain_quick_start.ipynb
> +    "    model_name=\"textembedding-gecko@latest\", project=project_id\n",
```suggestion
    "    model_name=\"textembedding-gecko@003\", project=project_id\n",
```

2024-02-22 23:56 UTC, tabbyl21 commented on samples/langchain_quick_start.ipynb
> +    "# Initialize the embedding service\n",
```suggestion
    "# Initialize the embedding service. In this case we are using version 003 of Vertex AI's textembedding-gecko model. In general, it is good practice to specify the model version used.\n",
```

2024-02-22 23:56 UTC, tabbyl21 commented on samples/langchain_quick_start.ipynb
> +    "Authenticate to Google Cloud as the IAM user logged into this notebook in order to access your Google Cloud Project."
```suggestion
    "In order to access your Google Cloud Project from this notebook, you will need to Authenticate as an IAM user."
```

2024-02-22 23:56 UTC, tabbyl21 commented on samples/langchain_quick_start.ipynb
> +    "> Indented block\n",
i think this is an error?

2024-02-23 00:21 UTC, tabbyl21 commented on samples/langchain_quick_start.ipynb
> +    "A **Postgres** Cloud SQL instance is required for the following stages of this notebook."
```suggestion
    "You will need a **Postgres** Cloud SQL instance for the following stages of this notebook."
```

2024-02-23 00:53 UTC, tabbyl21 commented on samples/langchain_quick_start.ipynb
> +    "| s6       | TV Show | Midnight Mass                  | Mike Flanagan               | Kate Siegel, Zach Gilford, Hamish Linklater, H...         | None
maybe we should show rows 1-5 instead

2024-02-23 00:53 UTC, tabbyl21 commented on samples/langchain_quick_start.ipynb
> +    "Now that you have data in your database, you are ready to use Cloud SQL Postgres as a document loader. This means we will pull data from the database and load it into memory as documents. This w
```suggestion
    "Now that you have data in your database, you are ready to use Cloud SQL Postgres as a document loader. This means we will pull data from the database and load it into memory as documents. We can then feed these documents into the vector store."
```

2024-02-23 00:53 UTC, tabbyl21 commented on samples/langchain_quick_start.ipynb
> +    "First lets install the core langchain library so that we can import the Document class to use when preparing documents to feed into our vector store."
we can cut this section since we are removing the pip install in the cell below

2024-02-23 00:53 UTC, tabbyl21 commented on samples/langchain_quick_start.ipynb
> +    "!pip install langchain_core"
+2

2024-02-23 00:53 UTC, tabbyl21 commented on samples/langchain_quick_start.ipynb
> +    "So far we've tested with using Cloud SQL Postgres as document loader, Vector Stoe and Chat Memory. Now let's use it in the `ConversationalRetrievalChain`.\n",
```suggestion
    "So far we've tested with using Cloud SQL Postgres as document loader, Vector Store and Chat Memory. Now let's use it in the `ConversationalRetrievalChain`.\n",
```

2024-02-23 00:56 UTC, tabbyl21 commented on samples/langchain_quick_start.ipynb
> +   ]
```suggestion
```

2024-02-23 00:58 UTC, tabbyl21 commented on samples/langchain_quick_start.ipynb
> +    "First let's initialize all of our PostgresSQLEngine object to use as a connection in our vector store and chat_history."
we init a postgresql connection earlier right, so we could use that here

2024-02-23 00:58 UTC, tabbyl21 commented on samples/langchain_quick_start.ipynb
> +    "pg_engine = PostgreSQLEngine.from_instance(\n",
we can cut this since we already init a connection string earlier

2024-02-23 01:04 UTC, totoleon commented on samples/langchain_quick_start.ipynb
> +    "vector_store = PostgresVectorStore.create_sync(\n",
Same as the other comment - I found the async methods can be problematic when running code in different blocks. It often complains about "attach to a different loop". Also eventually the chain will be using sync calls. So I used sync consistently whenever possible.

2024-02-23 06:01 UTC, tabbyl21 commented on samples/langchain_quick_start.ipynb
> +    "### Try load the documents to the vector table\n",
```suggestion
    "### Try inserting the documents into the vector table\n",
```

2024-02-23 15:37 UTC, kurtisvg approved these changes

2024-02-23 15:37 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "# Import the netflix titles table using gcloud command\n",
```suggestion
    "# Import the Netflix titles table using gcloud command\n",
```

2024-02-23 15:37 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "* How to use Cloud SQL Postgres for chat history storage"
The interface is a single word

2024-02-23 15:37 UTC, kurtisvg commented on samples/langchain_quick_start.ipynb
> +    "vector_store = PostgresVectorStore.create_sync(\n",
@averikitsch @tabbyl21 we should consider making this consistent -- not sure if this changes our decision from yesterday

2024-02-23 17:26 UTC, merged